/**
 * EKKE Token Webshop API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AddShippingAddressRequest { 
    user_id?: number;
    country: string;
    zip_code: string;
    city: string;
    street_name: string;
    street_type: string;
    house_number: string;
    apartment?: string;
    floor?: string;
    door?: string;
}

