/**
 * EKKE Token Webshop API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EditUserAddressRequest { 
    id: number;
    userId?: number;
    country?: string;
    zipCode?: string;
    city?: string;
    streetName?: string;
    streetType?: string;
    houseNumber?: string;
    apartment?: string;
    floor?: string;
    door?: string;
}

