export * from './addressApi.service';
import { AddressApiService } from './addressApi.service';
export * from './cartApi.service';
import { CartApiService } from './cartApi.service';
export * from './orderApi.service';
import { OrderApiService } from './orderApi.service';
export * from './productApi.service';
import { ProductApiService } from './productApi.service';
export * from './userApi.service';
import { UserApiService } from './userApi.service';
export const APIS = [AddressApiService, CartApiService, OrderApiService, ProductApiService, UserApiService];
