openapi: 3.0.0
info:
  title: EKKE Token Webshop API
  version: 1.0.0
servers:
  - url: http://localhost:4201
    description: Local server
paths:
  /allusers:
    get:
      summary: Returns a list of all users.
      tags:
        - userApi
      operationId: getAllUsers

  /adduser:
    post:
      summary: Creates a user.
      tags:
        - userApi
      operationId: addUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                name:
                  type: string
                neptun:
                  type: string
                email:
                  type: string
                password:
                  type: string
              required:
                - username
                - name
                - neptun
                - email
                - password

  /edituser/{id}:
    post:
      summary: Edits a user by id.
      tags:
        - userApi
      operationId: editUser
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                name:
                  type: string
                neptun:
                  type: string
                email:
                  type: string
                password:
                  type: string

  /deleteuser/{id}:
    delete:
      summary: Deletes a user by id.
      tags:
        - userApi
      operationId: deleteUser
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64

  /login:
    post:
      summary: Authorises a user.
      tags:
        - userApi
      operationId: login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
                - email
                - password

  /shatest:
    get:
      summary: Returns a hash for testing purposes.
      tags:
        - test
      operationId: testSHA

  /menProducts:
    get:
      summary: Returns an array of men products for the products page.
      tags:
        - productApi
      operationId: getMenProducts

  /womenProducts:
    get:
      summary: Returns an array of women products for the products page.
      tags:
        - productApi
      operationId: getWomenProducts

  /accessaryProducts:
    get:
      summary: Returns an array of accessary products for the products page.
      tags:
        - productApi
      operationId: getAccessaryProducts

  /productSlider:
    get:
      summary: Returns an array of all products for the product slider component.
      tags:
        - productApi
      operationId: getSliderProducts

  /product:
    get:
      summary: Returns a product for the product page.
      tags:
        - productApi
      operationId: getProduct
      parameters:
        - name: variantId
          in: query
          required: true
          schema:
            type: string

  /productSize:
    get:
      summary: Returns a product's size by variantId and color.
      tags:
        - productApi
      operationId: getProductSizeByVariantIdAndColor
      parameters:
        - name: variantId
          in: query
          required: true
          schema:
            type: string
        - name: color
          in: query
          required: true
          schema:
            type: string
