openapi: 3.0.0
info:
  title: EKKE Token Webshop API
  version: 1.0.0
servers:
  - url: http://localhost:4201
    description: Local server
paths:
  /user/get-all-users:
    get:
      summary: Returns a list of all users.
      tags:
        - userApi
      operationId: getAllUsers

  /user/add-user:
    post:
      summary: Creates a user.
      tags:
        - userApi
      operationId: addUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                name:
                  type: string
                neptun:
                  type: string
                email:
                  type: string
                password:
                  type: string
              required:
                - username
                - name
                - neptun
                - email
                - password

  /user/edit-user/{id}:
    post:
      summary: Edits a user by id.
      tags:
        - userApi
      operationId: editUser
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                name:
                  type: string
                neptun:
                  type: string
                email:
                  type: string
                password:
                  type: string

  /user/delete-user/{id}:
    delete:
      summary: Deletes a user by id.
      tags:
        - userApi
      operationId: deleteUser
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64

  /user/login:
    post:
      summary: Authorises a user.
      tags:
        - userApi
      operationId: login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
                - email
                - password

  /user-address/get-all-user-addresses:
    get:
      summary: Returns all user addresses.
      tags:
        - addressApi
      operationId: getAllUserAddresses

  /user-address/add-user-address:
    post:
      summary: Creates a user address associated with a user.
      tags:
        - addressApi
      operationId: addUserAddress
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: number
                country:
                  type: string
                zipCode:
                  type: string
                city:
                  type: string
                streetName:
                  type: string
                streetType:
                  type: string
                houseNumber:
                  type: string
                apartment:
                  type: string
                floor:
                  type: string
                door:
                  type: string
              required:
                - userId
                - country
                - zipCode
                - city
                - streetName
                - streetType
                - houseNumber

  /user-address/edit-user-address/{id}:
    post:
      summary: Edits a user address by id.
      tags:
        - addressApi
      operationId: editUserAddress
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: number
                country:
                  type: string
                zipCode:
                  type: string
                city:
                  type: string
                streetName:
                  type: string
                streetType:
                  type: string
                houseNumber:
                  type: string
                apartment:
                  type: string
                floor:
                  type: string
                door:
                  type: string

  /user-address/delete-user-address/{id}:
    delete:
      summary: Deletes a user address by id.
      tags:
        - addressApi
      operationId: deleteUserAddress
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64

  /order-address/get-all-order-addresses:
    get:
      summary: Returns all order addresses.
      tags:
        - addressApi
      operationId: getAllOrderAddresses

  /order-address/add-order-address:
    post:
      summary: Creates an order address.
      tags:
        - addressApi
      operationId: addOrderAddress
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                country:
                  type: string
                zipCode:
                  type: string
                city:
                  type: string
                streetName:
                  type: string
                streetType:
                  type: string
                houseNumber:
                  type: string
                apartment:
                  type: string
                floor:
                  type: string
                door:
                  type: string
              required:
                - country
                - zipCode
                - city
                - streetName
                - streetType
                - houseNumber

  /product/get-all-products:
    get:
      summary: Returns a list of all products.
      tags:
        - productApi
      operationId: getAllProducts

  /product/add-product:
    post:
      summary: Creates a product.
      tags:
        - productApi
      operationId: addProduct
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                variantId:
                  type: string
                name:
                  type: string
                type:
                  type: string
                style:
                  type: string
                color:
                  type: string
                size:
                  type: string
                price:
                  type: number
                quantity:
                  type: number
              required:
                - variantId
                - name
                - type
                - style
                - color
                - size
                - price
                - quantity

  /product/edit-product/{id}:
    post:
      summary: Edits a product by id.
      tags:
        - productApi
      operationId: editProduct
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                variantId:
                  type: string
                name:
                  type: string
                type:
                  type: string
                style:
                  type: string
                color:
                  type: string
                size:
                  type: string
                price:
                  type: number
                quantity:
                  type: number

  /product/delete-product/{id}:
    delete:
      summary: Deletes a product by id.
      tags:
        - productApi
      operationId: deleteProduct
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64

  /product/get-men-products:
    get:
      summary: Returns an array of men products for the products page.
      tags:
        - productApi
      operationId: getMenProducts

  /product/get-women-products:
    get:
      summary: Returns an array of women products for the products page.
      tags:
        - productApi
      operationId: getWomenProducts

  /product/get-accessary-products:
    get:
      summary: Returns an array of accessary products for the products page.
      tags:
        - productApi
      operationId: getAccessaryProducts

  /product/get-product-slider-all:
    get:
      summary: Returns an array of all products for the product slider component.
      tags:
        - productApi
      operationId: getSliderProducts

  /product/get-specific-product:
    get:
      summary: Returns a product for the product page.
      tags:
        - productApi
      operationId: getProduct
      parameters:
        - name: variantId
          in: query
          required: true
          schema:
            type: string

  /product/get-product-sizes:
    get:
      summary: Returns a product's sizes by variantId and color.
      tags:
        - productApi
      operationId: getProductSizesByVariantIdAndColor
      parameters:
        - name: variantId
          in: query
          required: true
          schema:
            type: string
        - name: color
          in: query
          required: true
          schema:
            type: string

  /product/get-product-colors:
    get:
      summary: Returns a product's colors by variantId and size.
      tags:
        - productApi
      operationId: getProductColorsByVariantIdAndSize
      parameters:
        - name: variantId
          in: query
          required: true
          schema:
            type: string
        - name: size
          in: query
          required: true
          schema:
            type: string

  /product/get-final-product:
    get:
      summary: Returns a product by the product's details.
      tags:
        - productApi
      operationId: getProductByDetails
      parameters:
        - name: variantId
          in: query
          required: true
          schema:
            type: string
        - name: color
          in: query
          required: true
          schema:
            type: string
        - name: size
          in: query
          required: true
          schema:
            type: string

  /cart/get-all-carts:
    get:
      summary: Returns a list of all carts.
      tags:
        - cartApi
      operationId: getAllCarts

  /cart/add-cart:
    post:
      summary: Creates a cart.
      tags:
        - cartApi
      operationId: addCart
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: number
                active:
                  type: number
              required:
                - userId
                - active

  /cart/edit-cart/{id}:
    post:
      summary: Edits a cart by id.
      tags:
        - cartApi
      operationId: editCart
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: number
                active:
                  type: number

  /cart/delete-cart/{id}:
    delete:
      summary: Deletes a cart by id.
      tags:
        - cartApi
      operationId: deleteCart
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64

  /cart/get-all-cart-items:
    get:
      summary: Returns a list of all cart items.
      tags:
        - cartApi
      operationId: getAllCartItems

  /cart/add-cart-item:
    post:
      summary: Creates a cart item.
      tags:
        - cartApi
      operationId: addCartItem
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: number
                cartId:
                  type: number
                productId:
                  type: number
                date:
                  type: date
              required:
                - userId
                - productId
                - date

  /cart/edit-cart-item/{id}:
    post:
      summary: Edits a cart item by id.
      tags:
        - cartApi
      operationId: editCartItem
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: number
                cartId:
                  type: number
                productId:
                  type: number
                date:
                  type: date

  /cart/delete-cart-item/{id}:
    delete:
      summary: Deletes a cart item by id.
      tags:
        - cartApi
      operationId: deleteCartItem
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64

  /cart/delete-cart-item-by-product-id-and-user-id/{productId}/{userId}:
    delete:
      summary: Deletes a cart item by product id and user id.
      tags:
        - cartApi
      operationId: deleteCartItemByProductIdAndUserId
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: userId
          in: path
          required: true
          schema:
            type: integer
            format: int64

  /cart/get-all-cart-product-by-user-id:
    get:
      summary: Returns a list of all products the user added to it's cart.
      tags:
        - cartApi
      operationId: getAllCartProductsByUserId
      parameters:
        - name: userId
          in: query
          required: true
          schema:
            type: number
