openapi: 3.0.0
info:
  title: EKKE Token Webshop API
  version: 1.0.0
servers:
  - url: http://localhost:4201
    description: Local server
paths:
  /all-users:
    get:
      summary: Returns a list of all users.
      tags:
        - userApi
      operationId: getAllUsers

  /add-user:
    post:
      summary: Creates a user.
      tags:
        - userApi
      operationId: addUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                name:
                  type: string
                neptun:
                  type: string
                email:
                  type: string
                password:
                  type: string
              required:
                - username
                - name
                - neptun
                - email
                - password

  /edit-user/{id}:
    post:
      summary: Edits a user by id.
      tags:
        - userApi
      operationId: editUser
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                name:
                  type: string
                neptun:
                  type: string
                email:
                  type: string
                password:
                  type: string

  /delete-user/{id}:
    delete:
      summary: Deletes a user by id.
      tags:
        - userApi
      operationId: deleteUser
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64

  /login:
    post:
      summary: Authorises a user.
      tags:
        - userApi
      operationId: login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
                - email
                - password

  /get-shipping-address:
    get:
      summary: Returns a shipping address by id.
      tags:
        - userApi
      operationId: getShippingAddress
      parameters:
        - name: id
          in: query
          required: true
          schema:
            type: string

  /add-shipping-address:
    post:
      summary: Creates a shipping address associated with a user.
      tags:
        - userApi
      operationId: addShippingAddress
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: number
                country:
                  type: string
                zip_code:
                  type: string
                city:
                  type: string
                street_name:
                  type: string
                street_type:
                  type: string
                house_number:
                  type: string
                apartment:
                  type: string
                floor:
                  type: string
                door:
                  type: string
              required:
                - country
                - zip_code
                - city
                - street_name
                - street_type
                - house_number

  /edit-shipping-address/{id}:
    post:
      summary: Edits a shipping address by id.
      tags:
        - userApi
      operationId: editShippingAddress
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                country:
                  type: string
                zip_code:
                  type: string
                city:
                  type: string
                street_name:
                  type: string
                street_type:
                  type: string
                house_number:
                  type: string
                apartment:
                  type: string
                floor:
                  type: string
                door:
                  type: string

  /delete-shipping-address/{id}:
    delete:
      summary: Deletes a shipping address by id.
      tags:
        - userApi
      operationId: deleteShippingAddress
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64

  /shatest:
    get:
      summary: Returns a hash for testing purposes.
      tags:
        - test
      operationId: testSHA

  /men-products:
    get:
      summary: Returns an array of men products for the products page.
      tags:
        - productApi
      operationId: getMenProducts

  /women-products:
    get:
      summary: Returns an array of women products for the products page.
      tags:
        - productApi
      operationId: getWomenProducts

  /accessary-products:
    get:
      summary: Returns an array of accessary products for the products page.
      tags:
        - productApi
      operationId: getAccessaryProducts

  /product-slider:
    get:
      summary: Returns an array of all products for the product slider component.
      tags:
        - productApi
      operationId: getSliderProducts

  /product:
    get:
      summary: Returns a product for the product page.
      tags:
        - productApi
      operationId: getProduct
      parameters:
        - name: variantId
          in: query
          required: true
          schema:
            type: string

  /product-sizes:
    get:
      summary: Returns a product's sizes by variantId and color.
      tags:
        - productApi
      operationId: getProductSizesByVariantIdAndColor
      parameters:
        - name: variantId
          in: query
          required: true
          schema:
            type: string
        - name: color
          in: query
          required: true
          schema:
            type: string

  /product-colors:
    get:
      summary: Returns a product's colors by variantId and size.
      tags:
        - productApi
      operationId: getProductColorsByVariantIdAndSize
      parameters:
        - name: variantId
          in: query
          required: true
          schema:
            type: string
        - name: size
          in: query
          required: true
          schema:
            type: string

  /product-final:
    get:
      summary: Returns a product by the product's details.
      tags:
        - productApi
      operationId: getProductByDetails
      parameters:
        - name: variantId
          in: query
          required: true
          schema:
            type: string
        - name: color
          in: query
          required: true
          schema:
            type: string
        - name: size
          in: query
          required: true
          schema:
            type: string
